export const TOGGLE_THEME = 'TOGGLE_THEME'
export const TOGGLE_LOADER = 'TOGGLE_LOADER'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const STORE_DATA = {
  VIDEOSDATA: 'VIDEOSDATA',
  CHANNELDATA: 'CHANNELDATA',
  COMMENTS: 'COMMENTS',
  SELECTEDVIDEOID: 'SELECTEDVIDEOID',
}
